export const categories = ['全部', '链表', '二叉树', '数组/窗口', '二分/TopK', '搜索/图', '动态规划', '模型手写', 'ASR 专项'];

// 统一工厂保证每张卡都可被 validateQuestionCard 校验，并让复习页仍可使用 approach。
const categoryGuide = {
  '链表': {
    bruteForce: (title) => `《${title}》可先把节点值或指针关系完整收集后重建；这能验证结果，但额外空间掩盖了原地指针操作。`,
    derivation: (focus) => [`先明确 ${focus} 中每个指针的职责。`, '画出断链前必须暂存的 next 关系。', '用两到三个节点演示一次完整的重连。'],
    invariant: (focus) => `链表处理中始终保留 ${focus} 所需的已处理链段入口和未处理链段入口。`,
    walkthrough: (title) => `演练《${title}》时，在纸上标出头、尾和临时指针，每次连边后检查是否仍能到达剩余节点。`,
    edgeCases: ['空链表', '单节点链表', '头节点或尾节点参与操作'],
    codeNotes: ['节点重连前先保存 next，避免断链。', 'dummy 节点能统一头部变化的分支。'],
    followUps: ['能否做到原地修改？', '若节点流式到达如何维护状态？'],
    followUpAnswers: ['多数链表题可用常数个指针原地完成，但要明确哪些节点仍被引用。', '只保留后续操作需要的边界节点或缓存窗口。'],
    pitfalls: ['覆盖 next 前没有暂存后继节点。', '头节点变化却没有 dummy 或新头变量。'],
  },
  '二叉树': {
    bruteForce: (title) => `《${title}》的基线做法是枚举根、路径或子树后逐一验证，通常会重复遍历同一子树。`,
    derivation: (focus) => [`确定 ${focus} 适合前序、后序还是层序。`, '定义递归返回值或队列中元素的精确含义。', '在空节点处给出可组合的基线。'],
    invariant: (focus) => `树遍历时，每个已完成子树都已产出 ${focus} 所需的正确摘要。`,
    walkthrough: (title) => `用三层小树演练《${title}》，逐次写出递归返回值或队列内容。`,
    edgeCases: ['空树', '退化为单链的树', '只有左子树或只有右子树'],
    codeNotes: ['递归终止条件先处理空节点。', 'BFS 每层开始前固定当前队列长度。'],
    followUps: ['递归深度过大如何处理？', '如何输出具体路径而非仅数值？'],
    followUpAnswers: ['可改为显式栈或迭代遍历以规避调用栈限制。', '在递归/回溯中维护父指针或路径数组。'],
    pitfalls: ['把子树返回值与全局答案混为一谈。', '遗漏空节点导致访问 left/right 出错。'],
  },
  '数组/窗口': {
    bruteForce: (title) => `《${title}》可枚举所有子数组或窗口再计算指标，复杂度常为 O(n²) 或更高。`,
    derivation: (focus) => [`识别 ${focus} 是否具有单调性或可增量维护性。`, '定义窗口左右端点和辅助结构保存的信息。', '证明每个元素进入和离开窗口次数有限。'],
    invariant: (focus) => `当前窗口始终满足 ${focus} 的约束，辅助结构准确反映窗口内元素。`,
    walkthrough: (title) => `演练《${title}》时逐项移动左右边界，并记录哈希表、队列或计数器变化。`,
    edgeCases: ['空数组', '窗口长度为 1', '重复值与全相同元素'],
    codeNotes: ['left 指针只能右移，避免重复扫描。', '队列中优先保存下标以便淘汰过期元素。'],
    followUps: ['如何返回区间而不只返回数值？', '数据流无限长时如何处理？'],
    followUpAnswers: ['更新最优答案时同时保存左右端点。', '维护固定大小窗口和可淘汰的增量统计。'],
    pitfalls: ['收缩窗口后忘记更新计数。', '用值而非下标导致无法判断元素是否过期。'],
  },
  '二分/TopK': {
    bruteForce: (title) => `《${title}》可线性扫描或完整排序得到答案，但没有利用有序性、堆或分区性质。`,
    derivation: (focus) => [`写出 ${focus} 的单调判定或目标秩。`, '确定闭区间或半开区间的含义。', '每轮排除不可能包含答案的一半或一组候选。'],
    invariant: (focus) => `答案始终位于当前搜索区间或 TopK 候选集合中，${focus} 没有被错误排除。`,
    walkthrough: (title) => `演练《${title}》时列出 l、r、mid（或堆顶）并说明每次淘汰理由。`,
    edgeCases: ['空数组', '目标不存在', '目标在首尾边界'],
    codeNotes: ['统一区间语义并在循环后验证候选。', 'TopK 的堆大小应严格受 k 限制。'],
    followUps: ['重复值如何改变判定？', '如何处理在线插入？'],
    followUpAnswers: ['重复值可能破坏严格单调，需要收缩边界或使用 lower_bound。', '维护大小受限的堆或平衡树。'],
    pitfalls: ['l/r 更新导致死循环或漏掉 mid。', '第 k 大和升序第 n-k 个下标混淆。'],
  },
  '搜索/图': {
    bruteForce: (title) => `《${title}》可不加剪枝地枚举所有路径或状态，分支数会快速爆炸。`,
    derivation: (focus) => [`把 ${focus} 表示为节点、边或回溯状态。`, '明确 visited/path 在何时写入和恢复。', '利用层数、排序或入度做剪枝。'],
    invariant: (focus) => `搜索前沿只包含 ${focus} 下尚未扩展且状态合法的候选。`,
    walkthrough: (title) => `演练《${title}》时画出一层搜索树或队列，标记访问和回溯恢复的位置。`,
    edgeCases: ['起点就是终点', '不存在可行路径', '存在环或重复状态'],
    codeNotes: ['BFS 入队时标记访问，避免重复入队。', '回溯函数退出前恢复现场。'],
    followUps: ['何时选 BFS 而不是 DFS？', '如何输出一条具体路径？'],
    followUpAnswers: ['无权最短步数使用 BFS；枚举组合或深度结构常用 DFS。', '保存 parent 或在 path 中记录选择。'],
    pitfalls: ['visited 标记时机错误造成重复搜索。', '回溯遗漏恢复导致后续分支被污染。'],
  },
  '动态规划': {
    bruteForce: (title) => `《${title}》的递归基线会重复计算相同子问题，通常呈指数增长。`,
    derivation: (focus) => [`把 ${focus} 写成状态定义。`, '枚举最后一次选择并建立转移。', '设置可验证的初始状态与遍历顺序。'],
    invariant: (focus) => `计算到当前下标时，所有更小子问题的 ${focus} 状态已是最优值。`,
    walkthrough: (title) => `用最小输入填一张《${title}》的 DP 表，解释每个格子来自哪个前驱。`,
    edgeCases: ['空输入', '只有一个状态', '目标不可达或全为负值'],
    codeNotes: ['转移依赖方向决定循环顺序。', '可压缩时只保留下一步真正依赖的状态。'],
    followUps: ['如何恢复具体方案？', '如何把空间压缩？'],
    followUpAnswers: ['记录选择或从最终状态按转移反向回溯。', '用滚动数组或有限个前驱变量替换整张表。'],
    pitfalls: ['dp 初值把不可达状态误设为 0。', '正序/倒序更新错误导致同一元素被重复使用。'],
  },
  '模型手写': {
    bruteForce: (title) => `《${title}》的朴素实现直接按定义展开张量运算，正确但常忽略数值稳定性与向量化。`,
    derivation: (focus) => [`从 ${focus} 的数学定义写出张量形状。`, '识别指数、归一化或索引中的数值稳定点。', '区分训练与推理时需要保存的状态。'],
    invariant: (focus) => `实现始终保持 ${focus} 的形状约束、概率归一化或尺度约束。`,
    walkthrough: (title) => `用一个极小张量演练《${title}》，逐步核对形状和中间数值。`,
    edgeCases: ['极大或极小 logits', 'batch 大小为 1', 'mask、padding 或空类别'],
    codeNotes: ['优先使用稳定的库算子和 keepdims/keepdim。', '注释每个张量的 batch、序列、通道维度。'],
    followUps: ['如何提升数值稳定性？', '如何降低显存或计算量？'],
    followUpAnswers: ['使用 log-sum-exp、减最大值、eps 与高精度累积。', '用分块、缓存、稀疏化或 fused kernel。'],
    pitfalls: ['softmax 前后 mask 顺序错误。', '张量维度或广播方向写反。'],
  },
  'ASR 专项': {
    bruteForce: (title) => `《${title}》可枚举所有对齐或转写路径再求和/比较，但路径数随帧数指数增长。`,
    derivation: (focus) => [`明确 ${focus} 的时间轴、标签轴和 blank 语义。`, '定义每个前缀或格点累计的概率/状态。', '在对数域合并多条等价路径。'],
    invariant: (focus) => `每步保存的分数完整覆盖 ${focus} 下所有合法历史，而不会重复或遗漏对齐路径。`,
    walkthrough: (title) => `演练《${title}》时写出两三帧的 token、blank 与前缀/状态转移。`,
    edgeCases: ['空音频帧', '连续 blank', '同一帧连续输出多个标签'],
    codeNotes: ['概率累积应在 log 域使用 log-sum-exp。', '流式场景要明确何时提交稳定前缀和截断缓存。'],
    followUps: ['如何融合语言模型？', '如何降低流式延迟？'],
    followUpAnswers: ['在 beam 扩展分数中加入语言模型权重和长度奖励。', '减小 chunk 和右上下文，并采用稳定前缀策略。'],
    pitfalls: ['把 blank 删除与重复合并顺序写反。', '缓存无限增长或状态没有随输出 token 更新。'],
  },
};

const q = (id, category, difficulty, title, prompt, quickAnswer, code, complexity, extra = {}) => {
  const guide = categoryGuide[category];
  const explanationFocus = extra.explanationFocus || `${title}：${quickAnswer}`;
  return ({
  id, category, difficulty, title, prompt, quickAnswer,
  approach: extra.approach || quickAnswer,
  explanationFocus,
  bruteForce: extra.bruteForce || guide.bruteForce(title),
  derivation: extra.derivation || guide.derivation(explanationFocus),
  invariant: extra.invariant || guide.invariant(explanationFocus),
  walkthrough: extra.walkthrough || guide.walkthrough(title),
  edgeCases: extra.edgeCases || guide.edgeCases,
  code, codeNotes: extra.codeNotes || guide.codeNotes,
  complexity,
  followUps: extra.followUps || guide.followUps,
  followUpAnswers: extra.followUpAnswers || guide.followUpAnswers,
  pitfalls: extra.pitfalls || guide.pitfalls,
});
};

const py = (body) => `# Python\n${body}`;

export const questions = [
  q('206', '链表', 'Easy', '反转链表', '原地反转单链表并返回新头。', '维护 prev、cur、nxt；先保存 nxt 再反转 cur.next。', py('prev=None\nwhile head:\n    nxt=head.next; head.next=prev\n    prev,head=head,nxt\nreturn prev'), '时间 O(n)，空间 O(1)', { invariant: 'prev 始终是已经反转好的前缀头结点。' }),
  q('92', '链表', 'Medium', '反转链表 II', '反转位置 left 到 right 的链表区间。', 'dummy 定位 left 前驱，反复把区间后续节点头插到该前驱之后。', py('dummy=ListNode(0,head); pre=dummy\nfor _ in range(left-1): pre=pre.next\ncur=pre.next\nfor _ in range(right-left):\n    move=cur.next; cur.next=move.next\n    move.next=pre.next; pre.next=move\nreturn dummy.next'), '时间 O(n)，空间 O(1)', { edgeCases: ['left=1', 'left=right', 'right 等于链表长度'] }),
  q('23', '链表', 'Hard', '合并 K 个升序链表', '合并 k 条有序链表。', '小根堆保存每条链表当前头；弹出最小节点后把它的 next 入堆。', py('heap=[]\nfor i,node in enumerate(lists):\n    if node: heappush(heap,(node.val,i,node))\nwhile heap:\n    _,i,node=heappop(heap)\n    tail.next=tail=node\n    if node.next: heappush(heap,(node.next.val,i,node.next))'), '时间 O(N log k)，空间 O(k)'),
  q('146', '链表', 'Medium', 'LRU Cache', '实现 O(1) 的 get/put 与最近最少使用淘汰。', '哈希表定位节点，双向链表维护新旧顺序；访问即移到头部，满时弹出尾部。', py('def get(key):\n    if key not in cache: return -1\n    move_front(cache[key]); return cache[key].val\ndef put(key,val):\n    if key in cache: cache[key].val=val; move_front(cache[key])\n    else: add_front(Node(key,val)); evict_if_needed()'), 'get/put 均 O(1)', { invariant: '链表从头到尾按最近使用到最久未使用排列。' }),
  q('21', '链表', 'Easy', '合并两个有序链表', '合并两条升序单链表。', 'dummy 尾指针每次接较小头，最后接上未耗尽的一条。', py('dummy=tail=ListNode()\nwhile a and b:\n    if a.val<b.val: tail.next,a=a,a.next\n    else: tail.next,b=b,b.next\n    tail=tail.next\ntail.next=a or b\nreturn dummy.next'), '时间 O(m+n)，空间 O(1)'),
  q('25', '链表', 'Hard', 'K 个一组翻转链表', '每 k 个节点翻转一次，尾部不足 k 个保留。', '先探测是否够 k 个，再把 [groupPrev.next, kth] 原地反转并接回。', py('while True:\n    kth=get_kth(groupPrev,k)\n    if not kth: break\n    groupNext=kth.next\n    prev,cur=groupNext,groupPrev.next\n    while cur!=groupNext: cur.next,prev,cur=prev,cur,cur.next\n    groupPrev.next,groupPrev=prev,groupPrev.next'), '时间 O(n)，空间 O(1)'),
  q('141', '链表', 'Easy', '环形链表', '判断单链表是否含环。', 'Floyd 快慢指针：有环时快指针最终追上慢指针。', py('slow=fast=head\nwhile fast and fast.next:\n    slow=slow.next; fast=fast.next.next\n    if slow is fast: return True\nreturn False'), '时间 O(n)，空间 O(1)'),
  q('142', '链表', 'Medium', '环形链表 II', '返回环的入口节点。', '相遇后一个指针回头，两指针每次一步，再次相遇即入口。', py('slow=fast=head\nwhile True:\n    slow=slow.next; fast=fast.next.next\n    if slow is fast: break\np=head\nwhile p is not slow: p=p.next; slow=slow.next\nreturn p'), '时间 O(n)，空间 O(1)', { edgeCases: ['无环（先处理 fast 为空）', '自环', '入口就是头结点'] }),
  q('160', '链表', 'Easy', '相交链表', '找两条单链表第一个公共节点。', 'a 走完接 b，b 走完接 a；总路程相同，最多第二轮相遇。', py('a,b=headA,headB\nwhile a is not b:\n    a=a.next if a else headB\n    b=b.next if b else headA\nreturn a'), '时间 O(m+n)，空间 O(1)'),

  q('102', '二叉树', 'Medium', '二叉树层序遍历', '按层返回二叉树节点值。', 'BFS 每轮先固定队列长度，恰好弹出这一层。', py('q=deque([root]); ans=[]\nwhile q:\n    ans.append([node.val for node in q])\n    for _ in range(len(q)):\n        node=q.popleft()\n        if node.left:q.append(node.left)\n        if node.right:q.append(node.right)'), '时间 O(n)，空间 O(w)'),
  q('103', '二叉树', 'Medium', '二叉树锯齿层序遍历', '按层交替从左到右和从右到左输出。', '普通 BFS，奇数层把当前层结果反转，或双端队列按方向插入。', py('level=[]\nfor _ in range(len(q)):\n    node=q.popleft(); level.append(node.val)\n    if node.left:q.append(node.left)\n    if node.right:q.append(node.right)\nif len(ans)%2: level.reverse()\nans.append(level)'), '时间 O(n)，空间 O(w)'),
  q('105', '二叉树', 'Medium', '前序与中序构造二叉树', '由 preorder 和 inorder 重建树。', '前序首元素为根；哈希表定位中序根，递归切分左右子树区间。', py('pos={v:i for i,v in enumerate(inorder)}\ndef build(pl,pr,il,ir):\n    if pl==pr:return None\n    root=TreeNode(preorder[pl]); k=pos[root.val]\n    left=k-il\n    root.left=build(pl+1,pl+1+left,il,k)\n    root.right=build(pl+1+left,pr,k+1,ir); return root'), '时间 O(n)，空间 O(n)'),
  q('124', '二叉树', 'Hard', '二叉树最大路径和', '路径可从任意节点开始结束，求最大节点和。', '后序返回“向下单臂最大贡献”；当前节点同时合并左右贡献更新全局答案。', py('best=-inf\ndef dfs(node):\n    global best\n    if not node:return 0\n    l=max(0,dfs(node.left)); r=max(0,dfs(node.right))\n    best=max(best,node.val+l+r)\n    return node.val+max(l,r)'), '时间 O(n)，空间 O(h)', { invariant: 'dfs 返回值只能是一条向下路径，不能同时带左右两支。' }),
  q('297', '二叉树', 'Hard', '二叉树序列化与反序列化', '把任意二叉树编码并可无歧义恢复。', '前序写值和 # 空标记；反序列化按相同顺序消费 token。', py('def ser(n): return "#" if not n else f"{n.val},{ser(n.left)},{ser(n.right)}"\ndef de(tokens):\n    x=next(tokens)\n    if x=="#":return None\n    n=TreeNode(int(x)); n.left=de(tokens); n.right=de(tokens); return n'), '时间 O(n)，空间 O(n)'),
  q('331', '二叉树', 'Medium', '验证二叉树前序序列化', '不用建树判断前序串是否合法。', '维护可用槽位：根消耗一个并产生两个；空节点只消耗一个。', py('slots=1\nfor token in preorder.split(","):\n    slots-=1\n    if slots<0:return False\n    if token!="#": slots+=2\nreturn slots==0'), '时间 O(n)，空间 O(1)'),
  q('236', '二叉树', 'Medium', '最近公共祖先', '普通二叉树中求 p、q 的最近公共祖先。', '后序：左右各找到一个则当前节点是 LCA，否则向上返回非空结果。', py('if not root or root is p or root is q:return root\nl=dfs(root.left); r=dfs(root.right)\nif l and r:return root\nreturn l or r'), '时间 O(n)，空间 O(h)'),

  q('3', '数组/窗口', 'Medium', '无重复字符的最长子串', '求不含重复字符的最长连续子串。', 'last 记录字符最近下标；left 只右移到冲突字符之后。', py('last={}; left=ans=0\nfor r,ch in enumerate(s):\n    if ch in last:left=max(left,last[ch]+1)\n    last[ch]=r; ans=max(ans,r-left+1)'), '时间 O(n)，空间 O(字符集)'),
  q('1', '数组/窗口', 'Easy', '两数之和', '返回和为 target 的两个下标。', '遍历时用哈希表查补数，查不到再记录当前值。', py('seen={}\nfor i,x in enumerate(nums):\n    if target-x in seen:return [seen[target-x],i]\n    seen[x]=i'), '时间 O(n)，空间 O(n)'),
  q('42', '数组/窗口', 'Hard', '接雨水', '计算柱状图能接住的雨水。', '双指针维护左右最高柱；较矮侧的积水只由该侧最高值决定。', py('l,r=0,len(h)-1; lm=rm=ans=0\nwhile l<r:\n    if h[l]<h[r]:\n        lm=max(lm,h[l]); ans+=lm-h[l]; l+=1\n    else:\n        rm=max(rm,h[r]); ans+=rm-h[r]; r-=1'), '时间 O(n)，空间 O(1)'),
  q('128', '数组/窗口', 'Medium', '最长连续序列', '无序数组求最长连续整数序列。', '集合中只从 x-1 不存在的起点向右扩展，避免重复扫描。', py('S=set(nums); best=0\nfor x in S:\n    if x-1 not in S:\n        y=x\n        while y in S:y+=1\n        best=max(best,y-x)'), '时间 O(n) 均摊，空间 O(n)'),
  q('239', '数组/窗口', 'Hard', '滑动窗口最大值', '返回每个长度 k 窗口的最大值。', '单调递减队列存下标，队首始终是窗口最大值候选。', py('dq=deque(); ans=[]\nfor i,x in enumerate(nums):\n    while dq and nums[dq[-1]]<=x:dq.pop()\n    dq.append(i)\n    if dq[0]<=i-k:dq.popleft()\n    if i>=k-1:ans.append(nums[dq[0]])'), '时间 O(n)，空间 O(k)'),
  q('334', '数组/窗口', 'Medium', '递增三元子序列', '判断是否存在 i<j<k 且 nums[i]<nums[j]<nums[k]。', '维护最小 first 和其后的最小 second；找到更大第三个数即可。', py('first=second=float("inf")\nfor x in nums:\n    if x<=first:first=x\n    elif x<=second:second=x\n    else:return True\nreturn False'), '时间 O(n)，空间 O(1)'),

  q('33', '二分/TopK', 'Medium', '搜索旋转排序数组', '在无重复旋转数组中找 target。', '每轮至少一侧有序，判断 target 是否落在有序侧以缩小区间。', py('l,r=0,len(nums)-1\nwhile l<=r:\n    m=(l+r)//2\n    if nums[m]==target:return m\n    if nums[l]<=nums[m]:\n        if nums[l]<=target<nums[m]:r=m-1\n        else:l=m+1\n    else:\n        if nums[m]<target<=nums[r]:l=m+1\n        else:r=m-1\nreturn -1'), '时间 O(log n)，空间 O(1)'),
  q('153', '二分/TopK', 'Medium', '寻找旋转排序数组最小值', '数组无重复，找旋转点最小值。', '和右端比较：mid 大于 right，最小值在右侧；否则保留 mid。', py('l,r=0,len(nums)-1\nwhile l<r:\n    m=(l+r)//2\n    if nums[m]>nums[r]:l=m+1\n    else:r=m\nreturn nums[l]'), '时间 O(log n)，空间 O(1)'),
  q('347', '二分/TopK', 'Medium', '前 K 个高频元素', '返回出现频率最高的 k 个元素。', 'Counter 后用大小 k 小根堆，或桶排序按频率收集。', py('cnt=Counter(nums); heap=[]\nfor x,f in cnt.items():\n    heappush(heap,(f,x))\n    if len(heap)>k:heappop(heap)\nreturn [x for _,x in heap]'), '时间 O(n log k)，空间 O(n)'),
  q('4', '二分/TopK', 'Hard', '两个正序数组中位数', '要求 O(log(min(m,n))) 求中位数。', '二分较短数组切分点，使左半全部不大于右半。', py('if len(a)>len(b):a,b=b,a\nl,r=0,len(a)\nwhile l<=r:\n    i=(l+r)//2; j=(len(a)+len(b)+1)//2-i\n    if a[i-1]>b[j]:r=i-1\n    elif b[j-1]>a[i]:l=i+1\n    else: return median_of_partition(i,j)'), '时间 O(log min(m,n))，空间 O(1)'),
  q('215', '二分/TopK', 'Medium', '数组第 K 大元素', '在无序数组找第 k 大。', 'Quickselect 只递归目标下标一边；平均比全排序快。', py('target=len(nums)-k\n# partition 后仅保留包含 target 的区间\nwhile l<=r:\n    p=partition(nums,l,r)\n    if p==target:return nums[p]\n    if p<target:l=p+1\n    else:r=p-1'), '平均 O(n)，最坏 O(n²)'),

  q('46', '搜索/图', 'Medium', '全排列', '返回无重复数组的所有排列。', '回溯维护 path 和 used；长度到 n 时复制答案。', py('def dfs():\n    if len(path)==len(nums):ans.append(path[:]);return\n    for i,x in enumerate(nums):\n        if not used[i]:\n            used[i]=1; path.append(x); dfs(); path.pop(); used[i]=0'), '时间 O(n·n!)，空间 O(n)'),
  q('78', '搜索/图', 'Medium', '子集', '返回数组的全部子集。', '每个元素只有选或不选两种分支，也可按起点枚举组合。', py('ans=[[]]\nfor x in nums:\n    ans += [s+[x] for s in ans]\nreturn ans'), '时间 O(n·2^n)，空间 O(n·2^n)'),
  q('39', '搜索/图', 'Medium', '组合总和', '元素可重复使用，找和为 target 的组合。', '递归从 start 开始，允许下一层仍使用当前下标以避免排列重复。', py('def dfs(start,remain):\n    if remain==0:ans.append(path[:]);return\n    for i in range(start,len(candidates)):\n        x=candidates[i]\n        if x>remain:break\n        path.append(x); dfs(i,remain-x); path.pop()'), '指数级，取决于解空间'),
  q('79', '搜索/图', 'Medium', '单词搜索', '在字母网格中判断是否能走出单词。', '从每格 DFS，当前路径临时标记访问，回溯时恢复。', py('def dfs(i,j,k):\n    if k==len(word):return True\n    if bad(i,j,k):return False\n    ch=board[i][j]; board[i][j]="#"\n    ok=any(dfs(i+di,j+dj,k+1) for di,dj in dirs)\n    board[i][j]=ch; return ok'), '时间 O(mn·4^L)，空间 O(L)'),
  q('994', '搜索/图', 'Medium', '腐烂的橘子', '求所有新鲜橘子腐烂的最少分钟。', '多源 BFS：所有腐烂橘子同时入队，每层代表一分钟。', py('q=deque(rotten); minutes=0\nwhile q and fresh:\n    for _ in range(len(q)):\n        i,j=q.popleft()\n        for ni,nj in neighbors(i,j):\n            if grid[ni][nj]==1:grid[ni][nj]=2; fresh-=1; q.append((ni,nj))\n    minutes+=1\nreturn minutes if fresh==0 else -1'), '时间 O(mn)，空间 O(mn)'),
  q('200', '搜索/图', 'Medium', '岛屿数量', '统计网格中四连通岛屿数量。', '扫描到陆地就计数并 DFS/BFS 淹没整个连通块。', py('for i in range(m):\n for j in range(n):\n  if grid[i][j]=="1":\n   ans+=1; flood(i,j)  # flood 将访问过的陆地改为 0'), '时间 O(mn)，空间 O(mn)'),

  q('53', '动态规划', 'Easy', '最大子数组和', '求连续子数组最大和。', 'Kadane：以当前位置结尾的最好和，要么从当前数重启要么接前缀。', py('best=cur=nums[0]\nfor x in nums[1:]:\n    cur=max(x,cur+x); best=max(best,cur)\nreturn best'), '时间 O(n)，空间 O(1)'),
  q('121', '动态规划', 'Easy', '买卖股票的最佳时机', '最多一次交易的最大利润。', '扫描中维护历史最低买入价，用当天卖出更新利润。', py('low=float("inf"); ans=0\nfor p in prices:\n    low=min(low,p); ans=max(ans,p-low)\nreturn ans'), '时间 O(n)，空间 O(1)'),
  q('198', '动态规划', 'Medium', '打家劫舍', '不能抢相邻房屋时的最大金额。', 'dp[i]=前 i 间最大值，转移为不抢 i 或抢 i 加 dp[i-2]。', py('prev2=prev1=0\nfor x in nums:\n    prev2,prev1=prev1,max(prev1,prev2+x)\nreturn prev1'), '时间 O(n)，空间 O(1)'),
  q('55', '动态规划', 'Medium', '跳跃游戏', '判断能否到达最后下标。', '贪心维护最远可达位置，遍历到不可达位置立即失败。', py('far=0\nfor i,step in enumerate(nums):\n    if i>far:return False\n    far=max(far,i+step)\nreturn True'), '时间 O(n)，空间 O(1)'),
  q('1143', '动态规划', 'Medium', '最长公共子序列', '求两个字符串的 LCS 长度。', '字符相等取左上加一，否则取上方和左方较大值。', py('dp=[[0]*(n+1) for _ in range(m+1)]\nfor i in range(1,m+1):\n for j in range(1,n+1):\n  dp[i][j]=dp[i-1][j-1]+1 if a[i-1]==b[j-1] else max(dp[i-1][j],dp[i][j-1])\nreturn dp[m][n]'), '时间 O(mn)，空间 O(mn)'),
  q('139', '动态规划', 'Medium', '单词拆分', '判断字符串能否由词典词拼出。', 'dp[i] 表示前 i 个字符可拆；枚举末词起点 j。', py('dp=[False]*(len(s)+1); dp[0]=True\nfor i in range(1,len(s)+1):\n    dp[i]=any(dp[j] and s[j:i] in words for j in range(i))\nreturn dp[-1]'), '时间 O(n²)，空间 O(n)'),
  q('416', '动态规划', 'Medium', '分割等和子集', '是否可分成和相等的两组。', '总和为奇数直接否；0/1 背包倒序更新能否凑到 sum/2。', py('if sum(nums)%2:return False\nt=sum(nums)//2; dp=[True]+[False]*t\nfor x in nums:\n    for s in range(t,x-1,-1):dp[s]|=dp[s-x]\nreturn dp[t]'), '时间 O(n·sum)，空间 O(sum)'),
  q('72', '动态规划', 'Hard', '编辑距离与 WER 回溯', '求编辑距离，并解释 WER 的 S/D/I 回溯。', 'dp 记录最少编辑；从右下沿取得最优的前驱反向走即可累计替换、删除、插入。', py('for i in range(1,m+1):\n for j in range(1,n+1):\n  dp[i][j]=dp[i-1][j-1] if ref[i-1]==hyp[j-1] else 1+min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1])\n# 回溯前驱，WER=(S+D+I)/len(ref)'), '时间 O(mn)，空间 O(mn)', { followUps: ['如何把空间压缩为 O(n)？', '为什么 WER 需要回溯？'], followUpAnswers: ['只需距离时保留两行；需要操作序列则保留父指针或重算。', '回溯才能区分相同距离中的替换、删除和插入。'] }),

  q('cross-entropy', '模型手写', 'Medium', '多分类 Cross Entropy', '手写稳定的 softmax 交叉熵。', '先减每行最大 logit，再 logsumexp；损失是正确类负对数概率。', py('z=logits-logits.max(axis=1,keepdims=True)\nlogp=z-np.log(np.exp(z).sum(axis=1,keepdims=True))\nloss=-logp[np.arange(len(y)),y].mean()'), '时间 O(B·C)，空间 O(B·C)', { invariant: '平移所有 logits 不改变 softmax 概率。' }),
  q('bce', '模型手写', 'Medium', '二分类 BCEWithLogits', '解释为何 BCE 应直接吃 logits。', '稳定公式 max(x,0)-x*y+log1p(exp(-abs(x)))，避免先 sigmoid 溢出。', py('def bce_logits(x,y):\n    return np.maximum(x,0)-x*y+np.log1p(np.exp(-np.abs(x)))'), '时间 O(n)，空间 O(n)'),
  q('batchnorm', '模型手写', 'Medium', 'BatchNorm', '训练和推理阶段 BN 有何不同。', '训练用当前 batch 均值方差并更新滑动统计；推理用 running mean/var。', py('mu=x.mean(axis=0); var=x.var(axis=0)\ny=gamma*(x-mu)/np.sqrt(var+eps)+beta\nrunning_mu=momentum*running_mu+(1-momentum)*mu'), '时间 O(元素数)，空间 O(C)'),
  q('dropout', '模型手写', 'Easy', 'Dropout', '实现 inverted dropout 并说明推理行为。', '训练时以 keep_prob 采样掩码并除以 keep_prob；推理直接恒等映射。', py('if training:\n    mask=(np.random.rand(*x.shape)<keep)/keep\n    return x*mask\nreturn x'), '时间 O(元素数)，空间 O(元素数)'),
  q('positional-encoding', '模型手写', 'Medium', '正弦位置编码', '写出 Transformer 的 sinusoidal 位置编码。', '偶数维用 sin(pos/10000^(2i/d))，奇数维用 cos，使相对位移可线性表达。', py('pos=np.arange(L)[:,None]; i=np.arange(0,d,2)\npe=np.zeros((L,d)); angle=pos/10000**(i/d)\npe[:,0::2]=np.sin(angle); pe[:,1::2]=np.cos(angle)'), '时间 O(Ld)，空间 O(Ld)'),
  q('topk-sampling', '模型手写', 'Medium', 'Top-K Sampling', '实现只在概率最高 k 个 token 中采样。', '取 top-k logits，把其余置为 -inf，重新 softmax 后按分布采样。', py('idx=np.argpartition(logits,-k)[-k:]\nmasked=np.full_like(logits,-np.inf); masked[idx]=logits[idx]\np=np.exp(masked-masked.max()); p/=p.sum()\nreturn rng.choice(len(p),p=p)'), '时间 O(V)，空间 O(V)'),
  q('beam-search', '模型手写', 'Hard', 'Beam Search', '解释束搜索的状态、打分和终止。', '每步扩展每条 beam 的 top 候选，累计 logprob，保留全局前 beam_size 条。', py('beams=[([],0.0)]\nfor _ in range(max_len):\n    cand=[]\n    for seq,score in beams:\n        for tok,lp in top_tokens(seq):cand.append((seq+[tok],score+lp))\n    beams=sorted(cand,key=lambda x:x[1],reverse=True)[:beam_size]'), '时间 O(T·beam·V)，空间 O(beam·T)'),
  q('kmeans', '模型手写', 'Medium', 'K-Means', '写出 KMeans 的 E/M 两步并说明空簇处理。', 'E 步分配最近中心，M 步取簇均值；空簇可重置为最远样本。', py('for _ in range(iters):\n    label=((x[:,None]-centers[None])**2).sum(-1).argmin(1)\n    for k in range(K):\n        if np.any(label==k): centers[k]=x[label==k].mean(0)'), '每轮 O(nKd)，空间 O(nK)'),
  q('iou', '模型手写', 'Easy', 'IoU', '计算两个 xyxy 框的 Intersection over Union。', '交集宽高取 max(0, min(right)-max(left))，再除并集。', py('iw=max(0,min(a[2],b[2])-max(a[0],b[0]))\nih=max(0,min(a[3],b[3])-max(a[1],b[1]))\ninter=iw*ih\nreturn inter/(area(a)+area(b)-inter+1e-9)'), '时间 O(1)，空间 O(1)'),
  q('nms', '模型手写', 'Medium', 'NMS', '按置信度抑制重叠检测框。', '按分数降序取最高框，删除与它 IoU 超阈值的剩余框，直到为空。', py('keep=[]\norder=scores.argsort()[::-1]\nwhile len(order):\n    i=order[0]; keep.append(i)\n    order=order[1:][iou(boxes[i],boxes[order[1:]])<thr]'), '朴素 O(n²)，空间 O(n)'),
  q('convolution', '模型手写', 'Medium', '二维卷积输出尺寸', '解释卷积输出尺寸和 im2col 思路。', '单边输出 floor((W+2P-K)/S)+1；对每个滑窗与卷积核逐元素乘加。', py('out=(W+2*P-K)//S+1\nfor oy in range(out):\n for ox in range(out):\n  patch=padded[oy*S:oy*S+K,ox*S:ox*S+K]\n  y[oy,ox]=(patch*kernel).sum()'), '直接实现 O(HW·K²)，空间 O(HW)'),
  q('attention', '模型手写', 'Hard', '缩放点积 Attention', '实现 Attention(Q,K,V)=softmax(QKᵀ/√d + mask)V。', '先算 score 并除以 √d 控制方差；mask 在 softmax 前置为负无穷，再与 V 相乘。', py('scores = Q @ K.transpose(-1, -2) / math.sqrt(Q.shape[-1])\nif mask is not None:\n    scores = scores.masked_fill(~mask, float("-inf"))\nweights = scores.softmax(dim=-1)\noutput = weights @ V'), '时间 O(L²d)，空间 O(L²)', {
    derivation: ['QKᵀ 给出每个 query 对所有 key 的相似度。', '缩放防止 d 较大时 softmax 饱和。', 'softmax 后每一行是对 value 的凸组合。'],
    invariant: '每个未被 mask 的 query 行权重和为 1，且被 mask 的位置概率为 0。',
    walkthrough: '用两个 query、三个 key 的小矩阵，先算一行分数，再 softmax 并加权 value。',
    edgeCases: ['全为 mask 的行需要避免产生 NaN', 'causal mask 不能看到未来 token', '注意 batch/head 维度广播'],
    codeNotes: ['mask 必须在 softmax 之前应用。', '实际框架中应使用稳定的 fused softmax。'],
    followUps: ['为什么是除以 √d 而不是 d？', 'Self Attention 与 Cross Attention 有何差异？'],
    followUpAnswers: ['点积方差随 d 增大，除以 √d 可将量级稳定在常数。', 'Self 的 Q/K/V 来自同一序列；Cross 的 Q 来自解码器，K/V 来自编码器。'],
    pitfalls: ['把 mask 放到 softmax 后会破坏归一化。', '漏掉缩放会使大维度下梯度变差。'],
  }),
  q('rmsnorm', '模型手写', 'Medium', 'RMSNorm', '手写 RMSNorm，并与 LayerNorm 比较。', '沿 hidden 维计算均方根，不减均值；归一化后只乘可学习 scale。', py('def rmsnorm(x, weight, eps=1e-6):\n    rms = (x.pow(2).mean(dim=-1, keepdim=True) + eps).sqrt()\n    return x / rms * weight'), '时间 O(元素数)，额外空间 O(1)', {
    derivation: ['计算每个 token 的均方根 rms。', 'x/rms 把向量尺度归一。', '用 weight 恢复每个通道的可学习缩放。'],
    invariant: '归一化维度固定为最后一维 hidden size，eps 位于开方前。',
    walkthrough: '对向量 [3,4]，rms=√((9+16)/2)，逐维相除后再乘 weight。',
    edgeCases: ['全零向量依赖 eps 防除零', '输入可含 batch 与序列维', '半精度下 eps 不能过小'],
    codeNotes: ['RMSNorm 不需要减均值，也通常没有 bias。', 'keepdim 保证能与原输入广播。'],
    followUps: ['与 LayerNorm 的关键差异？', '为什么常用于大语言模型？'],
    followUpAnswers: ['LayerNorm 还会中心化并除标准差；RMSNorm 只控制尺度。', '计算略少且在实践中训练稳定，常作为 Transformer 的归一化层。'],
    pitfalls: ['误把均方根写成均值。', 'mean 的维度写错会跨 token 归一化。'],
  }),
  q('conv1d', '模型手写', 'Medium', '一维卷积', '手写单通道一维卷积并计算输出长度。', '每个输出位置取长度 K 的窗口与卷积核点积；长度为 floor((L+2P-K)/S)+1。', py('def conv1d(x, kernel, stride=1, pad=0):\n    x = np.pad(x, (pad, pad))\n    out_len = (len(x) - len(kernel)) // stride + 1\n    return np.array([(x[i*stride:i*stride+len(kernel)] * kernel).sum()\n                     for i in range(out_len)])'), '时间 O(L·K)，空间 O(L)', {
    derivation: ['先在时间轴两端补零。', '滑窗以 stride 移动，每次与 kernel 点积。', '多通道时对输入通道求和并为每个输出通道使用一组核。'],
    invariant: '第 i 个输出只读取补零后从 i·stride 开始的连续 K 个采样点。',
    walkthrough: '输入 [1,2,3]、核 [1,1]、stride=1 时依次得到 3、5。',
    edgeCases: ['核长大于有效输入', 'stride 大于 1', 'padding 导致边界窗口含零'],
    codeNotes: ['深度学习库通常实现的是互相关，不会翻转 kernel。', '实际张量布局还要处理 batch、channel 维。'],
    followUps: ['dilation 如何改变感受野？', 'Conv1d 如何用于语音？'],
    followUpAnswers: ['采样窗口内部间隔 dilation，感受野增大而参数量不变。', '可沿时间轴提取局部声学模式，stride 同时实现下采样。'],
    pitfalls: ['把卷积翻核与框架互相关语义混淆。', '输出长度公式漏掉 padding 或 stride。'],
  }),

  q('ctc-greedy', 'ASR 专项', 'Medium', 'CTC Greedy Decode', '把逐帧 argmax token 解码为文本。', '先合并连续重复 token，再删除 blank；顺序不能颠倒。', py('out=[]; prev=None\nfor t in tokens:\n    if t!=prev and t!=blank:out.append(t)\n    prev=t\nreturn out'), '时间 O(T)，空间 O(T)', { pitfalls: ['先删 blank 会把 a, blank, a 错误合并。', 'argmax 只给局部最优，不等于全局最优转写。'] }),
  q('ctc-prefix-beam', 'ASR 专项', 'Hard', 'CTC Prefix Beam Search', '说明 prefix beam 为什么维护 p_blank 和 p_nonblank。', '同一前缀以 blank/nonblank 结尾的转移不同；分开累计才能正确处理重复字符。', py('for prefix in beams:\n    pb,pnb=score[prefix]\n    next[prefix].blank += (pb+pnb)*p(blank)\n    for c in vocab_no_blank:\n        # c==last 时只能从 blank 扩展同前缀\n        update_prefix(prefix,c,pb,pnb)'), '时间约 O(T·beam·V)，空间 O(beam)', { followUps: ['如何融合语言模型？', '为什么要做 log-sum-exp？'], followUpAnswers: ['扩展分数时加上 λ·LM(prefix+c) 和长度奖励。', '同一前缀有多条对齐路径，概率应相加；对数域用 log-sum-exp。'] }),
  q('rnnt', 'ASR 专项', 'Hard', 'RNN-T 前向递推', '解释 RNN-T 的 t/u 二维格点与 blank、label 转移。', 'encoder 推进时间 t，prediction 网络推进标签 u；blank 走 (t+1,u)，标签走 (t,u+1)。', py('alpha[0,0]=0\nfor t in range(T+1):\n for u in range(U+1):\n  alpha[t+1,u]=logadd(alpha[t+1,u],alpha[t,u]+logp_blank[t,u])\n  alpha[t,u+1]=logadd(alpha[t,u+1],alpha[t,u]+logp_label[t,u])'), '时间 O(TU)，空间 O(TU)'),
  q('rnnt-greedy', 'ASR 专项', 'Hard', 'RNN-T Greedy Decode', '实现 RNN-T 的时间同步贪心解码。', '每个 encoder 帧反复取 joint 网络最大 token；若是 blank 则前进到下一帧，否则输出 token 并更新 prediction state。', py('state = predictor.start()\nfor t in range(T):\n    for _ in range(max_symbols_per_frame):\n        token = joint(encoder[t], state).argmax()\n        if token == blank: break\n        output.append(token)\n        state = predictor.step(token, state)'), '时间 O(T·M·V)，空间 O(U)', {
    derivation: ['encoder 先产生当前声学帧表示。', 'blank 表示当前帧不再发标签并推进时间。', '非 blank 标签不推进时间，但会更新预测网络状态。'],
    invariant: '在同一时间帧内，只有预测到 blank 才能推进 t；输出标签必须更新 prediction state。',
    walkthrough: '若 t=0 依次输出 “你”“好” 后遇到 blank，才进入 t=1。',
    edgeCases: ['连续 blank', '单帧输出多个 token', '必须设置每帧最大输出数防止死循环'],
    codeNotes: ['实际实现通常使用 logit argmax，不必先 softmax。', 'max_symbols_per_frame 是延迟与死循环保护。'],
    followUps: ['与 CTC greedy 的最大差别？', '如何提高准确率？'],
    followUpAnswers: ['RNN-T 的非 blank 不推进时间且依赖 prediction 网络；CTC 每帧只选一个独立 token。', '用 beam search、语言模型融合或更强的 encoder/predictor。'],
    pitfalls: ['预测到非 blank 后忘记更新 prediction state。', '没有 blank 或上限保护会导致单帧无限循环。'],
  }),
  q('streaming-cache', 'ASR 专项', 'Hard', '流式 ASR 缓存', 'Transformer/Conformer 流式识别如何缓存。', '缓存历史 KV 或左上下文；每个 chunk 只算新增帧，并控制右上下文带来的延迟。', py('cache=init_cache()\nfor chunk in stream:\n    y,cache=encoder(chunk,cache,left_context=L)\n    partial=decoder.step(y,decoder_cache)\n    emit_stable_prefix(partial)'), '每 chunk 约 O(chunk·context)，缓存 O(context)', { followUps: ['如何降低首字延迟？', '缓存为何要截断？'], followUpAnswers: ['减小 chunk 和右上下文，或使用更早的稳定前缀策略。', '无限缓存会使计算和显存随音频长度线性增长。'] }),
];
