export function makeResumeCard({
  id,
  category,
  title,
  prompt,
  quickAnswer,
  why,
  implementation,
  tradeoffs,
  evaluation,
  prerequisites,
  workedExample,
  edgeCases,
  pitfalls,
  followUps,
  complexity,
  difficulty = 'Hard',
  order,
}) {
  return {
    id,
    category,
    difficulty,
    ...(order ? { order } : {}),
    title,
    prompt,
    quickAnswer,
    explanationFocus: `是什么：${quickAnswer}`,
    approach: implementation,
    code: `def evidence_gate(primary_gain: float, guardrail_ok: bool, reproducible: bool) -> dict:\n    \"\"\"把简历主张变成可复核的上线证据，而不是只报一个最好数字。\"\"\"\n    release = primary_gain > 0 and guardrail_ok and reproducible\n    return {\"primary_gain\": primary_gain, \"guardrail_ok\": guardrail_ok,\n            \"reproducible\": reproducible, \"release\": release}`,
    complexity,
    beginnerSummary: `面试时不要只背名词。先说清“${title}”解决什么问题，再给机制、对照实验、失败边界和上线守护。`,
    diagram: '业务问题 → 技术机制 → 对照实验 → 失败切片 → 上线守护',
    derivation: [
      `为什么需要：${why}`,
      `怎么实现：${implementation}`,
      `有什么代价：${tradeoffs}`,
      `怎么评测：${evaluation}`,
    ],
    prerequisites,
    workedExample,
    lineByLine: [
      'evidence_gate 接收主指标增益、护栏是否通过、结果能否复现三类证据。',
      'release 只有在主指标变好、旧域或线上护栏通过且多次实验可复现时才为真。',
      '返回完整证据而非单个布尔值，便于答辩、评审、灰度与复盘。',
    ],
    edgeCases,
    followUps,
    pitfalls,
    kind: 'concept',
  };
}
