export default {
  id: 'as-hotword', category: 'ASR 专项', difficulty: 'Medium', kind: 'code',
  title: '热词增强怎样提召回又不乱插词',
  prompt: '不重新训练声学模型时，怎样增强人名、品牌等热词，并控制误触发？',
  quickAnswer: '可在解码时加入 context graph/WFST、浅融合语言模型或受约束的 token bias。增大 boost 通常提高热词召回，也会增加无热词音频中的错误插入；因此必须同时在含热词集和负样本集上调参，不能只看命中率。',
  beginnerSummary: '热词增强像给解码器一张“今天可能出现的名字”清单。提示太弱听不出来，提示太强又会把相似发音都写成热词。',
  explanationFocus: '热词增强改变的是候选路径分数，不是凭空修好声学证据；必须同时控制正样本召回和负样本误插入。',
  approach: '把热词按 tokenizer 拆成 token 路径，在前缀匹配时逐步加分，完成词后给完成奖励；用开发集扫描 boost 和回退惩罚。',
  derivation: ['为什么需要：专有词在训练语料中稀少，默认语言先验容易压过声学证据。', '怎么实现：将热词编成前缀图，并在 beam search 中携带图状态与加分。', '有什么代价：热词表越大，图状态和候选扩展越多；高 boost 会误插相似词。', '怎么评测：报告热词召回、热词错误率、负样本误插率、整体 CER/WER 和延迟。'],
  prerequisites: ['Beam Search 与 top-k', 'WFST 与 BPE 分词'],
  workedExample: ['示意：将“科大讯飞”拆成模型 token，只有前缀连续匹配时逐步奖励。', '在不含该词的相似发音集上若误插增加，就降低 boost 或加入完成/回退约束。'],
  code: "def contextual_score(prefix, token, graph_state, boost):\n    next_state, matched = graph_state.step(token)\n    bonus = boost if matched else 0.0\n    return next_state, bonus",
  lineByLine: ['根据当前图状态尝试消费新 token。', '只有匹配合法热词前缀时才加分。', '真实系统还需处理完整词奖励、回退和多个热词共享前缀。'],
  complexity: '开销取决于 beam、热词图活跃状态数和分词长度；不能笼统写成固定 O(V)。',
  diagram: '声学分数 + 基础 LM 分数 + 热词图增量分数 ─▶ beam 排序\n                                      └▶ 正集召回 / 负集误插共同调参',
  edgeCases: ['多个热词共享前缀时不能提前给完整词奖励。', '热词含 tokenizer 未覆盖字符时需要规范化或改写。', '短热词与常用词同音时误触发风险最高。'],
  pitfalls: ['只报热词命中率，不报告无热词负样本上的误插入。', '直接对整个词表统一加 bias，既浪费计算又缺少前缀约束。'],
  followUps: [{ question: '热词为什么不一定需要重训？', answer: '它可以只改变解码搜索分数；若声学模型根本分不清对应音素，解码增强也有上限。' }, { question: '热词表很大怎么办？', answer: '用 trie/FST 共享前缀、按会话或领域缩小激活集合，并监控活跃状态数和延迟。' }],
};
