export default {
  id: 'as-whisper', category: 'ASR 专项', difficulty: 'Medium', kind: 'code',
  title: 'Whisper 的训练方式、控制 token 与边界',
  prompt: 'Whisper 为什么有较强的零样本鲁棒性？控制 token、30 秒窗口和自回归解码分别意味着什么？',
  quickAnswer: 'Whisper 用约 68 万小时多语言、多任务弱监督数据训练标准 Transformer encoder-decoder，并用特殊 token 指定语言、转录/翻译和时间戳任务。规模和任务多样性带来较强零样本迁移，但不保证每种语言或领域都好；其原始推理以 30 秒窗口和自回归解码为中心，也不是天然的低延迟流式模型。',
  beginnerSummary: 'Whisper 像听过大量网络音频的多语种转录员。开始工作前要告诉它语言和任务；它见得多，所以换场景常能直接用，但噪声、专业词、长音频和低延迟仍可能出问题。',
  explanationFocus: '能力来自大规模多任务弱监督，而不是“标准 Transformer 本身自动拥有零样本能力”。',
  approach: '音频转 log-Mel 后由 encoder 编码；decoder 以 start、language、task、timestamp 等控制 token 开始自回归生成，并对长音频分窗与去重。',
  derivation: ['为什么需要：逐语言训练专用模型难覆盖长尾语言与多种语音任务。', '怎么实现：把转录、翻译、语言识别和时间戳统一为 token 序列预测。', '有什么代价：自回归解码较慢，弱监督会带来噪声，静音和分布外音频可能幻觉。', '怎么评测：按语言、口音、噪声、长音频和专业词切片报告 WER/CER、幻觉率、延迟和显存。'],
  prerequisites: ['Transformer 编码器-解码器', 'log-Mel 与多任务学习'],
  workedExample: ['示意：中文音频使用 language=zh、task=transcribe；若改成 translate，目标变成英文翻译。', '纯静音输入也必须单独测试；模型若生成常见句子，应由 VAD、无语音概率或后处理拦截。'],
  code: "def whisper_request(mel, language, task):\n    prompt = [START, language_token(language), task_token(task)]\n    return autoregressive_decode(mel, prompt, timestamps=True)",
  lineByLine: ['先明确语言和转录/翻译任务。', '控制 token 作为 decoder 的起始上下文。', '真实解码还要处理温度、停止条件、时间戳和长音频窗口。'],
  complexity: 'encoder 注意力随固定窗口内帧数增长；decoder 逐 token 自回归，延迟还受 beam、窗口重叠和模型尺寸影响。',
  diagram: 'waveform ─▶ 30 s log-Mel ─▶ Transformer encoder ─▶ autoregressive decoder ─▶ text / timestamps\n                                         ▲ language + task control tokens',
  references: [{ title: 'Robust Speech Recognition via Large-Scale Weak Supervision', url: 'https://arxiv.org/abs/2212.04356' }],
  edgeCases: ['静音或纯噪声可能出现幻觉文本。', '相近语言或中途切换语种会让语言控制更复杂。', '跨窗口句子可能重复、漏字或时间戳错位。'],
  pitfalls: ['写成“68 万小时”时误写成“68 万=68,000”；论文规模是约 680,000 小时。', '给出“中文 WER 约 4%”却不说明数据集、归一化与模型版本。'],
  followUps: [{ question: 'Whisper 能做流式吗？', answer: '可以通过滑窗、局部确认和缓存做近似流式，但这属于系统改造；原始模型并非因果流式架构。' }, { question: '设置语言 token 后结果一定更好吗？', answer: '不一定。已知单语场景可减少误判；代码切换或语言标签错误时，强制语言反而可能伤害结果。' }],
};
