export default {
  id: 'asr-lid', category: 'ASR 专项', difficulty: 'Medium', kind: 'code',
  title: 'LID 辅助任务何时帮助或伤害 ASR',
  prompt: '语种识别 LID 与 ASR 共享 encoder 时，怎样判断是否存在梯度冲突，并选择调权、分头或 PCGrad？',
  quickAnswer: '辅助 LID 可能提供语言条件，也可能因标签噪声、数据不平衡或梯度方向冲突拖累 ASR。先分别记录两任务指标、共享层梯度余弦与范数，再用 loss 权重扫描、stop-gradient、较晚分叉或梯度投影做对照。PCGrad 是候选方法，不是看到负收益后的默认答案。',
  beginnerSummary: '让同一个模型一边听写、一边判断语言，两个老师有时方向一致，有时会拉扯。先量出是谁在拉、拉多大，再决定调小辅助任务、让它晚点分叉，还是修改梯度。',
  explanationFocus: '多任务负迁移有多种原因；梯度冲突必须被测量和对照实验支持。',
  approach: '按 batch 记录共享层两任务梯度余弦、范数和语种分布；依次比较 ASR-only、共享、调权、stop-gradient/分叉和投影方案。',
  derivation: ['为什么需要：LID 可帮助多语种路由与语言条件，但弱标签会向共享表征注入噪声。', '怎么实现：分别求 ASR 与 LID 对共享参数的梯度，监控方向和尺度，再做受控干预。', '有什么代价：逐任务求梯度增加训练开销，过度隔离也会失去正迁移。', '怎么评测：同时报告逐语种 ASR 错误率、LID 混淆矩阵、梯度统计和多 seed 稳定性。'],
  prerequisites: ['多任务共享编码器与梯度冲突', '多语种与语言识别'],
  workedExample: ['示意：ASR-only 稳定，共享训练后低资源语种退化；先检查该语种 LID 标签与采样比例。', '若负余弦集中在同一训练阶段，调低 LID 权重后消失且 ASR 恢复，才支持“梯度干扰”解释。'],
  code: "def gradient_cosine(asr_grad, lid_grad, eps=1e-12):\n    numerator = dot(asr_grad, lid_grad)\n    denominator = norm(asr_grad) * norm(lid_grad) + eps\n    return numerator / denominator",
  lineByLine: ['分子衡量两个梯度方向的内积。', '除以范数后得到 [-1, 1] 的方向相似度。', '余弦只是诊断信号，不能单独证明因果。'],
  complexity: '若同一 batch 分别反传两项 loss，梯度诊断会增加反向计算和显存；可按间隔抽样记录。',
  diagram: 'speech ─▶ shared encoder ─┬▶ ASR head / loss ─▶ g_asr\n                            └▶ LID head / loss ─▶ g_lid\n                  监控方向与范数 ─▶ 调权 / 分叉 / 投影',
  edgeCases: ['code-switch 片段只有一个句级语言标签时监督本身含糊。', '高资源语言 batch 主导梯度会掩盖低资源语种。', '梯度余弦接近零但 LID 范数极大时仍可能干扰。'],
  pitfalls: ['把某次 LID 准确率写成通用证据，或看到低准确率就断言有梯度冲突。', '不做 ASR-only 和 stop-gradient 对照就直接上 PCGrad。'],
  followUps: [{ question: '负梯度余弦一定有害吗？', answer: '不一定。瞬时负余弦可能是正常优化噪声，应结合长期统计、任务指标和干预对照判断。' }, { question: '什么时候直接拆成独立 LID 更合适？', answer: '当路由必须先于 ASR、LID 数据/延迟要求独立，或共享训练长期负迁移时，独立小模型可能更清晰。' }],
};
