export default {
  id: 'tts-vits', category: '语音合成', difficulty: 'Hard', kind: 'concept',
  title: 'VITS 的训练路径与推理路径为什么不同',
  prompt: 'VITS 中 posterior encoder、text prior、flow、duration predictor、decoder 与 discriminator 分别做什么？',
  quickAnswer: '训练时 posterior encoder 从真实声学谱得到潜变量 z，flow 把 z 映射到与文本 prior 对齐的空间；MAS 学习文本—声学单调对齐，duration predictor 学时长，decoder 从 z 生成波形，discriminator 提供对抗与特征匹配信号。推理时没有真实语音，先从文本 prior 采样 z_p，再经逆 flow 得到 z，并用预测时长和 decoder 生成波形。',
  beginnerSummary: '训练时模型能看到“标准录音”，先把它编码成隐藏声音，再学会怎样仅从文本猜到同类隐藏声音；推理时标准录音不存在，所以必须从文本一侧采样并反向通过 flow。',
  explanationFocus: 'VITS 的难点是理解训练有 posterior、推理无 posterior，以及 flow 在两个潜空间间可逆变换。',
  approach: '分别画训练图和推理图，再把 KL、duration、mel/feature、adversarial 与 feature-matching loss 对应到具体模块。',
  derivation: ['为什么需要：级联 mel+vocoder 的目标分离，且文本到语音是一对多分布。', '怎么实现：条件 VAE、normalizing flow、单调对齐、随机时长和 GAN 波形解码联合训练。', '有什么代价：多模块多损失耦合，判别器、KL 和对齐任一失衡都可能导致训练不稳。', '怎么评测：自然度/相似度、ASR 回识、时长与 F0、长句失败率，并用消融验证各模块。'],
  prerequisites: ['VAE 变分与 KL 散度', 'Normalizing Flow', 'GAN 与判别器', '时长与 forced alignment'],
  workedExample: ['训练：真实谱→posterior z→flow→z_p，与文本 prior 对齐；decoder(z) 重建波形。', '推理：文本 prior→采样 z_p→inverse flow→z→decoder；posterior encoder 完全不参与。'],
  code: "def vits_inference(text, noise_scale):\n    prior, durations = text_prior_and_duration(text)\n    z_prior = sample(prior, scale=noise_scale)\n    z = inverse_flow(z_prior, text_condition=text)\n    return waveform_decoder(expand_by_duration(z, durations))",
  lineByLine: ['文本侧产生 prior 参数和时长。', 'noise_scale 控制采样变化，但不是独立“情感旋钮”。', '逆 flow 把 prior 空间样本还原到 decoder 使用的潜空间。'],
  complexity: '推理以并行卷积/flow 为主，计算随声学/波形长度增长；训练还包含 posterior、判别器和多项损失，远重于单次推理。',
  diagram: '训练：spectrum ─▶ posterior z ─▶ flow ─▶ z_p ◀─ text prior\n                         └▶ decoder ─▶ waveform ─▶ discriminator\n推理：text prior ─▶ sample z_p ─▶ inverse flow ─▶ z ─▶ decoder',
  references: [{ title: 'VITS: Conditional Variational Autoencoder with Adversarial Learning for End-to-End TTS', url: 'https://arxiv.org/abs/2106.06103' }],
  edgeCases: ['MAS 对齐跳字会直接造成漏读或重复。', '判别器过强时生成器可能只追逐局部纹理。', '小数据微调可能把信道特征写进说话人表示。'],
  pitfalls: ['把 posterior encoder 写进线上推理必经路径。', '只看 KL 或 adversarial loss 选择最终 checkpoint。'],
  followUps: [{ question: 'flow 为什么需要可逆？', answer: '训练要把 posterior z 映射到 prior 空间计算密度/对齐，推理又要把 prior 样本映回 decoder 空间。' }, { question: 'VITS 是否完全不需要中间声学表示？', answer: '线上输出不必显式生成 mel，但训练 posterior 和重建损失仍会使用声学谱等表示。' }],
};
