export default {
  id: 'tts-llm-tts', category: '语音合成', difficulty: 'Hard', kind: 'concept',
  title: 'Codec Language Model TTS：tokenizer 不等于生成器',
  prompt: 'VALL-E、AudioPaLM 与 SoundStream 分别扮演什么角色？为什么不能把它们都称为同一种 TTS 模型？',
  quickAnswer: 'SoundStream 是神经音频 codec，把波形压成离散码并解码回波形，本身不根据文本完成 TTS。VALL-E 把文本条件下的 codec token 预测建模为语言模型，可用短参考音频作声学提示。AudioPaLM 是同时处理文本和语音的多模态语言模型，范围包含理解、识别、翻译与生成。三者分别是表示工具、codec LM TTS 例子和统一多模态模型，不能画成一条固定通用架构。',
  beginnerSummary: 'codec 像把声音变成编号的压缩器；VALL-E 学会“看文本和参考声音续写编号”；AudioPaLM 的目标更宽，还要听懂、转写和翻译。',
  explanationFocus: '先区分 audio tokenizer/codec、token 生成模型和最终 waveform decoder 三种职责。',
  approach: '画清 text token、acoustic prompt、semantic/acoustic codebook 与 codec decoder 的输入输出，并注明模型是否自回归、是否分层生成。',
  derivation: ['为什么需要：离散音频 token 让序列模型能统一处理文本与声音条件。', '怎么实现：codec 编码参考/目标音频，LM 预测目标 token，再由 codec decoder 还原波形。', '有什么代价：token 序列很长、层间建模复杂，且 prompt 会携带信道、情绪甚至隐私信息。', '怎么评测：文本可懂度、自然度、说话人相似、prompt 内容泄漏、长句稳定、延迟与 token 生成成本。'],
  prerequisites: ['VQ 码本与 codec', '大模型与 token 序列', '说话人 d-vector 与声纹'],
  workedExample: ['参考音频只负责提供声学提示；目标文本换成新句子，模型预测新句子的 codec token。', '若输出同时复制参考中的背景噪声，说明 prompt 表征没有只保留音色，也带入了信道。'],
  code: "def codec_lm_tts(text, reference_audio):\n    prompt_codes = audio_codec.encode(reference_audio)\n    target_codes = language_model.generate(text_tokens(text), prompt_codes)\n    return audio_codec.decode(target_codes)",
  lineByLine: ['codec 先把参考音频离散化。', '生成模型以文本和声学提示预测目标音频 token。', 'codec decoder 把目标 token 还原为波形；这只是通用草图。'],
  complexity: '成本取决于 codec 帧率、码本层数和生成方式；自回归 token 越多，串行延迟越大。',
  diagram: 'reference audio ─▶ codec encoder ─▶ acoustic prompt codes ─┐\ntext ─▶ text tokenizer ───────────────────────────────────────────────┼▶ token generator ─▶ codec decoder ─▶ waveform\nSoundStream：codec；VALL-E：codec token LM；AudioPaLM：更广的文本/语音统一模型',
  references: [{ title: 'VALL-E: Neural Codec Language Models are Zero-Shot TTS Synthesizers', url: 'https://arxiv.org/abs/2301.02111' }, { title: 'AudioPaLM: A Large Language Model That Can Speak and Listen', url: 'https://arxiv.org/abs/2306.12925' }, { title: 'SoundStream: An End-to-End Neural Audio Codec', url: 'https://arxiv.org/abs/2107.03312' }],
  edgeCases: ['参考音频含他人说话或背景音乐会污染 prompt。', '很短提示可能无法稳定估计音色和韵律。', '模型可能复现训练音频片段或被滥用于冒充，需授权、水印和滥用防护。'],
  pitfalls: ['把 SoundStream 写成直接从文本生成声音的 TTS。', '把论文中的 zero-shot 能力表述成所有说话人、语言和录音条件都无需验证。'],
  followUps: [{ question: '为什么参考音频可能同时带入环境声？', answer: 'codec prompt 通常编码完整声学信息，不保证音色、韵律和信道完全解耦。' }, { question: '语义 token 与声学 token 必须分开吗？', answer: '不是统一要求；不同模型使用不同 codec 和生成分解，需按具体论文说明。' }],
};
