export default {
  id: 'tts-hifigan', category: '语音合成', difficulty: 'Medium', kind: 'concept',
  title: 'HiFi-GAN：生成器、MPD 与 MSD 各看什么',
  prompt: 'HiFi-GAN 怎样把 mel 上采样成波形？多周期判别器 MPD 与多尺度判别器 MSD 有什么区别？',
  quickAnswer: '生成器用转置卷积逐级上采样，并用不同 kernel/dilation 的残差块组成多感受野融合。MPD 按多个周期把一维波形 reshape 成二维结构，检查周期性细节；MSD 在原始波形及下采样尺度上检查不同时间分辨率。原始 HiFi-GAN 的 MSD 不是“多个 STFT 分辨率判别器”；是否实时取决于具体配置、硬件和音频长度。',
  beginnerSummary: '生成器先把低帧率频谱放大成高采样率波形。判别器像两组质检员：MPD 专看不同音高周期是否像真声音，MSD 分别近看和远看波形结构。',
  explanationFocus: 'MPD 建模周期结构，MSD 建模不同时间尺度；不要与后来常见的多分辨率频谱判别器混淆。',
  approach: '先校验 mel hop_length 与上采样倍率乘积，再分别监控 adversarial、feature matching 和 mel reconstruction 信号。',
  derivation: ['为什么需要：mel 丢失相位和细粒度波形，简单回归容易产生过平滑声音。', '怎么实现：并行卷积生成器上采样，MPD/MSD 对抗训练，feature matching 稳定生成器。', '有什么代价：GAN 易不稳定，转置卷积和上采样设计不当会产生周期伪影。', '怎么评测：盲听、频谱/周期伪影、ASR 回识、RTF、峰值内存和 unseen speaker/声学模型泛化。'],
  prerequisites: ['GAN 与判别器', 'mel 频谱与 STFT', 'CNN 卷积与 depthwise'],
  workedExample: ['mel hop_length=256 时，所有上采样 stride 的乘积应为 256，生成长度才能与帧数一致。', 'MPD 使用周期 p reshape 波形；当长度不能整除 p 时先 padding，而不是直接丢尾部。'],
  code: "def hifigan_generator(mel):\n    x = pre_convolution(mel)\n    for upsample, residual_bank in stages:\n        x = upsample(x)\n        x = average([block(x) for block in residual_bank])\n    return tanh(post_convolution(x))",
  lineByLine: ['先把 mel channel 投影到生成器隐藏通道。', '每层先上采样，再融合多个感受野残差块。', '输出限制到波形幅度范围；真实实现还需严格匹配 kernel 和 padding。'],
  complexity: '生成计算随输出采样点数和通道数增长；纯卷积允许并行，但不能脱离配置和硬件直接承诺 RTF<1。',
  diagram: 'mel ─▶ pre-conv ─▶ upsample + MRF × N ─▶ post-conv ─▶ waveform\nwaveform ─┬▶ MPD：多个周期 reshape\n          └▶ MSD：原始 / 下采样多个尺度',
  references: [{ title: 'HiFi-GAN: Generative Adversarial Networks for Efficient and High Fidelity Speech Synthesis', url: 'https://arxiv.org/abs/2010.05646' }],
  edgeCases: ['上采样倍率与 hop_length 不一致会导致时长错位。', 'padding 或 kernel 组合可能造成边界爆音。', '只在真值 mel 上训练的 vocoder 遇到预测 mel 会有域偏移。'],
  pitfalls: ['把 MSD 解释成不同 STFT 分辨率；那是另一类频谱判别/损失设计。', '复制一个未定义 MRF、通道也不匹配的类，却标成可运行实现。'],
  followUps: [{ question: 'feature matching loss 做什么？', answer: '让生成音频与真音频在判别器中间层表示接近，为生成器提供比真假标签更平滑的训练信号。' }, { question: '为什么 MPD 对语音重要？', answer: '有声语音包含与基频相关的周期结构，多个周期视角能捕获不同音高范围和谐波细节。' }],
};
