export default {
  id: 'tts-g2p', category: '语音合成', difficulty: 'Medium', kind: 'concept',
  title: '中文 G2P：词典、上下文模型与回退怎样仲裁',
  prompt: '多音字、人名、专名和中英混读同时存在时，怎样设计可解释的 G2P 级联与置信度回退？',
  quickAnswer: '先做文本归一化、分词与语言跨度识别，再让高精度短语/专名词典、上下文多音字模型和规则/通用拼音工具各承担明确范围。仲裁要保存来源、置信度和冲突；阈值应在独立金标上按实体类型校准。不存在所有项目通用的“词典→G2PW→pypinyin”固定三级最优顺序，词典质量和业务风险决定谁能强制覆盖。',
  beginnerSummary: '“银行”和“行走”的“行”读音不同。系统先看完整词和上下文，再看专名词典；实在不确定才用覆盖广但不够聪明的默认规则，并记录自己为什么这么读。',
  explanationFocus: 'G2P 是带来源和置信度的候选仲裁，不是三个库按固定 if/else 串起来就结束。',
  approach: '冻结多音字/人名/数字/code-switch 金标；每个候选输出 phoneme、source、confidence，按类型校准阈值并保留可热更新词典。',
  derivation: ['为什么需要：中文字符到读音依赖词义和上下文，专名与混读又持续变化。', '怎么实现：TN/分词/LID→高精度词典→上下文模型→规则回退→冲突与 OOV 日志。', '有什么代价：词典维护成本高，模型置信度未校准会错误覆盖，分词错误还会传递。', '怎么评测：音节/声调准确率、实体切片、覆盖率—错误率曲线和最终 TTS 回识/听测。'],
  prerequisites: ['G2P 音素与发音', '正字法归一化', '多语种与语言识别', '置信度阈值与校准'],
  workedExample: ['“银行行长”先按词级上下文切分，两个“行”分别由短语或上下文模型给出读音与来源。', '罕见人名模型置信度不足时进入白名单/人工词典，而不是无条件接受默认单字音。'],
  code: "def resolve_pronunciation(span, context, resources):\n    candidates = resources.collect_candidates(span, context)\n    calibrated = [resources.calibrate(c, entity_type(span)) for c in candidates]\n    return resources.policy.choose(calibrated)",
  lineByLine: ['词典、上下文模型和规则都可提供候选。', '置信度按人名、普通词等实体类型分别校准。', '策略选择结果时保留来源，便于纠错与热修。'],
  complexity: 'Trie 词典匹配通常近似随文本长度增长；上下文模型成本取决于 encoder；真正工程成本还包括词典版本和 OOV 闭环。',
  diagram: 'text ─▶ TN / 分词 / LID ─▶ 候选：短语词典 + 上下文模型 + 规则\n                               └▶ 类型化校准 / 冲突仲裁 ─▶ phoneme + source + confidence',
  edgeCases: ['词典边界与分词结果冲突。', '人名、地名和普通词需要不同阈值。', '英文缩写在中文句中可能按字母名或单词发音。'],
  pitfalls: ['词典命中就永远强制覆盖；自动生成的低质量词典也会错。', '把某套具体三级回退描述成自己一定实施过的项目流程。'],
  followUps: [{ question: '为什么需要校准而不只看 softmax 最大值？', answer: '模型原始分数不一定等于真实正确概率，且在人名、普通词、不同域上的可靠性不同。' }, { question: '线上发现错读怎样热修？', answer: '优先用带版本和作用域的高精度短语词典修复，同时把样本回流金标集，避免永久堆叠不可审计规则。' }],
};
