// gen-cards.mjs — single source of truth = cards/<id>.js
//  - First run (cards/ empty): bootstrap every card out of questions.js into its own file.
//  - Every run: read cards/*.js, sort by id, and regenerate questions.js as a bundle.
//  Never hand-edit questions.js. Edit a card in cards/<id>.js, then `npm run gen`.

import { readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const cardsDir = path.join(root, 'cards');
const questionsPath = path.join(root, 'questions.js');

const HEADER = `// AUTO-GENERATED by scripts/gen-cards.mjs — DO NOT EDIT BY HAND.
// Source of truth = ./cards/<id>.js (one file per card). Edit a card there, then run: npm run gen
// This bundle is regenerated from cards/ on every build/test.

`;

const cardToFile = (card) => `export default ${JSON.stringify(card, null, 2)};\n`;

const importFresh = (filePath) =>
  import(pathToFileURL(filePath).href + `?t=${Date.now()}`);

async function bootstrap() {
  const mod = await importFresh(questionsPath);
  const questions = mod.questions;
  if (!Array.isArray(questions)) {
    throw new Error('questions.js has no array export — abort bootstrap');
  }
  mkdirSync(cardsDir, { recursive: true });
  let n = 0;
  for (const card of questions) {
    if (!card || !card.id) throw new Error('card without id encountered during bootstrap');
    writeFileSync(path.join(cardsDir, `${card.id}.js`), cardToFile(card));
    n++;
  }
  console.log(`bootstrapped ${n} cards -> cards/`);
}

async function readCards() {
  const files = readdirSync(cardsDir).filter((f) => f.endsWith('.js'));
  const cards = [];
  for (const f of files) {
    const mod = await importFresh(path.join(cardsDir, f));
    if (!mod.default || typeof mod.default !== 'object') {
      throw new Error(`cards/${f} has no default object export`);
    }
    cards.push(mod.default);
  }
  cards.sort((a, b) => String(a.id).localeCompare(String(b.id)));
  return cards;
}

async function main() {
  const hasCards =
    existsSync(cardsDir) && readdirSync(cardsDir).filter((f) => f.endsWith('.js')).length > 0;
  if (!hasCards) {
    console.log('cards/ empty — bootstrapping from questions.js');
    await bootstrap();
  }
  const cards = await readCards();
  if (cards.length === 0) throw new Error('no cards found in cards/');
  const bundle = HEADER + `export const questions = ${JSON.stringify(cards, null, 2)};\n`;
  writeFileSync(questionsPath, bundle);
  console.log(`wrote questions.js (${cards.length} cards)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
