// gen-cards.mjs — single source of truth = cards/<category>/<id>.js (grouped by category)
//  - First run (cards/ empty): bootstrap every card out of questions.js into cards/<category>/<id>.js.
//  - Every run: recursively read cards/**/*.js, sort by category→kind→id, regenerate questions.js bundle.
//  Never hand-edit questions.js. Edit a card in cards/<category>/<id>.js, then `npm run gen`.

import { readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const cardsDir = path.join(root, 'cards');
const questionsPath = path.join(root, 'questions.js');

const HEADER = `// AUTO-GENERATED by scripts/gen-cards.mjs — DO NOT EDIT BY HAND.
// Source of truth = ./cards/<category>/<id>.js (one file per card, grouped by category).
// Edit a card there, then run: npm run gen. This bundle is regenerated from cards/ on every build/test.

`;

// sanitize a category string into a filesystem-safe directory name
const sanitize = (s) => String(s).trim().replace(/[\\/:*?"<>|]/g, '_');
const catDir = (card) => sanitize(card.category || 'uncategorized');
const cardToFile = (card) => `export default ${JSON.stringify(card, null, 2)};\n`;
const importFresh = (filePath) => import(pathToFileURL(filePath).href + `?t=${Date.now()}`);

// recursively collect *.js files, but SKIP top-level files (cards/<id>.js are legacy flats
// that have been copied into cards/<category>/<id>.js). Only descend into category subdirs.
function listCardFiles(dir, isRoot = true) {
  const out = [];
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listCardFiles(full, false));
    else if (entry.isFile() && entry.name.endsWith('.js') && !isRoot) out.push(full);
  }
  return out;
}

async function bootstrap() {
  const mod = await importFresh(questionsPath);
  const questions = mod.questions;
  if (!Array.isArray(questions)) {
    throw new Error('questions.js has no array export — abort bootstrap');
  }
  let n = 0;
  for (const card of questions) {
    if (!card || !card.id) throw new Error('card without id encountered during bootstrap');
    const dir = path.join(cardsDir, catDir(card));
    mkdirSync(dir, { recursive: true });
    writeFileSync(path.join(dir, `${card.id}.js`), cardToFile(card));
    n++;
  }
  console.log(`bootstrapped ${n} cards -> cards/<category>/`);
}

async function readCards() {
  const files = listCardFiles(cardsDir);
  const cards = [];
  for (const f of files) {
    const mod = await importFresh(f);
    if (!mod.default || typeof mod.default !== 'object') {
      throw new Error(`${f} has no default object export`);
    }
    cards.push(mod.default);
  }
  // stable, grouped output: category → kind → id
  cards.sort(
    (a, b) =>
      String(a.category).localeCompare(String(b.category)) ||
      String(a.kind).localeCompare(String(b.kind)) ||
      String(a.id).localeCompare(String(b.id))
  );
  return cards;
}

async function main() {
  if (listCardFiles(cardsDir).length === 0) {
    console.log('cards/ empty — bootstrapping from questions.js');
    await bootstrap();
  }
  const cards = await readCards();
  if (cards.length === 0) throw new Error('no cards found in cards/');
  const bundle = HEADER + `export const questions = ${JSON.stringify(cards, null, 2)};\n`;
  writeFileSync(questionsPath, bundle);
  console.log(`wrote questions.js (${cards.length} cards, grouped by category→kind→id)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
